services:
  postgres:
    image: postgres:17.4
    container_name: secure-note
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notepad
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

volumes:
  pgdata:

